version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SQLImpUniversal312
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "SQLImpUniversal312", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  etl:
    build: .
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - TARGET_DB_URL=mssql+pyodbc://sa:SQLImpUniversal312@sqlserver:1433/ImpUniversal?driver=ODBC+Driver+17+for+SQL+Server
      - SOURCE_DB_URL=mssql+pyodbc://host.docker.internal/WideWorldImporters?driver=ODBC+Driver+17+for+SQL+Server&Trusted_Connection=yes
    ports:
      - "8000:8000"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# SQLtester123